name: Docker Image CI for LLM Interaction Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'llm_interaction_service/**'
      - '.github/workflows/llm-interaction-service-docker-publish.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'llm_interaction_service/**'
      - '.github/workflows/llm-interaction-service-docker-publish.yml'

jobs:
  build-and-push:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v4
#
#    - name: Log in to the Container registry
#      uses: docker/login-action@v3
#      with:
#        registry: ghcr.io
#        username: ${{ secrets.GHCR_USERNAME }}
#        password: ${{ secrets.GHCR_PAT }}
#
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v3
#
#    - name: Build and push
#      uses: docker/build-push-action@v5
#      with:
#        context: ./llm_interaction_service
#        file: ./llm_interaction_service/Dockerfile
##        push: ${{ github.event_ame != 'pull_request' }}
#        tags: ghcr.io/${{ github.repository_owner }}/doc-intellect-llm-interaction-service:production
##        cache-from: type=gha
##        cache-to: type=gha,mode=max
#        secrets: |
#          llm-env=${{ secrets.LLM_PROD_ENV }}
#
#    - name: Show pushed image URL
#      run: "echo Pushed image: ghcr.io/${{ github.repository_owner }}/doc-intellect-llm-interaction-service:production"
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PAT }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./llm_interaction_service
          file: ./llm_interaction_service/Dockerfile
          push: true
          tags: registry.gitlab.com/${{ secrets.REGISTRY_PROJECT }}/llm-interaction-service:latest
